//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class index_blogposts:public drogon::DrTemplate<index_blogposts>
{
public:
	index_blogposts(){};
	virtual ~index_blogposts(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
